server:
  port: 8761


eureka:
  instance:
    hostname: localhost
    registry:
      expected-number-of-renews-per-min: 0


  client:
    registerWithEureka: false
    fetchRegistry: false

  server:
    enable-self-preservation: true
#    peer-eureka-status-refresh-time-interval-ms: 60000
#    renewal-percent-threshold: 0.49



#    eviction-interval-timer-in-ms: 45000
#    waitTimeInMsWhenSyncEmpty: 0

