### Spring properties
# Service registers under this name
spring:
  application:
    name: saludo-microservice
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

#Component Info
info:
 component: saludo-microservice


# HTTP Server (Tomcat) Port
server:
  port: 0


# Discovery Server Access
eureka:
    instance:
          instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}



    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/


      healthcheck:
        enabled: true

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false

#Service Registration Method
cloud:
 services:
  registrationMethod: route

  #Disable HTTP Basic Authentication
security:
 basic:
  enabled: false
